import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/_staticpages/navbar/page";
import Footer from "./(components)/_staticpages/footer/page";
import { ReduxProvider } from "./providers";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1920px] m-auto`}>
        <ReduxProvider>
          <Navbar />
          <div className="px-0 sm:px-12  bg-gradient-to-br from-blue-100 via-white to-blue-100">{children}</div>
          <ToastContainer />
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
